name: cs124
channels:
  - defaults
dependencies:
  - pip
  - pip:
      - torch==2.6.0
      - numpy==2.1.3
      - transformers==4.39.3
      - datasets==2.20.0
      - tiktoken==0.7.0
      - wandb==0.17.6
      - tqdm==4.66.4

